apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
spec:
  secretName: test-cert-tls
  duration: 24h
  renewBefore: 1h
  subject:
    organizations:
    - example.com
  commonName: example.com
  isCA: true
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: test-selfsigned
    kind: Issuer
