name: docs-runme

on:
  pull_request:
    branches:
      - '**'

  repository_dispatch:
    types: [trigger-workflow]

jobs:
  test-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file-path:
          - vcluster/deploy/topologies/multi-namespace-mode.mdx

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Runme CLI
        run: npm install -g runme

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install vcluster CLI
        run: |
          version=${{ github.event.inputs.version || '0.20.0-beta.9' }}
          curl -LO "https://github.com/loft-sh/vcluster/releases/download/v${version}/vcluster-linux-amd64"
          chmod +x ./vcluster-linux-amd64
          sudo mv ./vcluster-linux-amd64 /usr/local/bin/vcluster

      - name: Set up kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Run documentation tests with Runme
        run: |
          runme run -a --skip-prompts --filename ${{ matrix.file-path }}
